# Generated by Django 6.0.6 on 2026-07-04 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_profile_resume_url_profile_resume_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='certification',
            name='certificate_file',
            field=models.FileField(blank=True, null=True, upload_to='certificates/'),
        ),
        migrations.AddField(
            model_name='education',
            name='certificate_file',
            field=models.FileField(blank=True, help_text='Upload internship certificate', null=True, upload_to='certificates/'),
        ),
        migrations.AddField(
            model_name='education',
            name='is_internship',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='experience',
            name='certificate_file',
            field=models.FileField(blank=True, help_text='Upload internship certificate', null=True, upload_to='certificates/'),
        ),
        migrations.AddField(
            model_name='experience',
            name='is_internship',
            field=models.BooleanField(default=False),
        ),
    ]
