# Generated by Django 5.2.15 on 2026-07-04 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='resume_url',
        ),
        migrations.AddField(
            model_name='profile',
            name='resume_file',
            field=models.FileField(blank=True, help_text='Upload your resume PDF', null=True, upload_to='resume/'),
        ),
    ]
