# Generated by Django 5.2.15 on 2026-07-09 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_certification_certificate_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image_blend_amount',
            field=models.IntegerField(default=45, help_text='Percentage of picture covered by the bottom fade (e.g. 45)'),
        ),
    ]
