# Generated by Django 5.2.15 on 2026-07-14 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_profile_image_blend_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certification',
            name='certificate_file',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to='certificates/'),
        ),
        migrations.AlterField(
            model_name='education',
            name='certificate_file',
            field=models.FileField(blank=True, help_text='Upload internship certificate', max_length=500, null=True, upload_to='certificates/'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='certificate_file',
            field=models.FileField(blank=True, help_text='Upload internship certificate', max_length=500, null=True, upload_to='certificates/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='profile/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='resume_file',
            field=models.FileField(blank=True, help_text='Upload your resume PDF', max_length=500, null=True, upload_to='resume/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='projects/'),
        ),
    ]
