# Generated by Django 5.2.15 on 2026-07-14 13:25

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_certification_certificate_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certification',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='certification',
            name='order',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='education',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='order',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='experience',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='order',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='order',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='order',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='skill',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='skill',
            name='order',
            field=models.IntegerField(db_index=True, default=0),
        ),
    ]
